name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-assertions:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environments
        run: |
            ./.github/scripts/ci-checkout.sh
            ./.github/scripts/ci-setup.sh

      # Run the tests with assertions
      - name: Dacapo Test (with extreme_assertions)
        run: ./.github/scripts/ci-test-assertions.sh
